version: "3"

services:
  namenode:
    image: closetool/hadoop-namenode:2.0.0-hadoop3.3.6-java11
    container_name: namenode
    hostname: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - ./hack/hadoop_namenode:/hadoop/dfs/name
      - ./hack/input:/input
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hack/hadoop.env

  datanode:
    image: closetool/hadoop-datanode:2.0.0-hadoop3.3.6-java11
    container_name: datanode
    restart: always
    volumes:
      - ./hack/hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hack/hadoop.env

  resourcemanager:
    image: closetool/hadoop-resourcemanager:2.0.0-hadoop3.3.6-java11
    container_name: resourcemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./hack/hadoop.env

  nodemanager1:
    image: closetool/hadoop-nodemanager:2.0.0-hadoop3.3.6-java11
    container_name: nodemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hack/hadoop.env

  historyserver:
    image: closetool/hadoop-historyserver:2.0.0-hadoop3.3.6-java11
    container_name: historyserver
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - ./hack/hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hack/hadoop.env
